# Generated by Django 2.0.6 on 2018-06-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('block_users', models.ManyToManyField(related_name='_user_block_users_+', to='members.User')),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='members.User')),
            ],
        ),
    ]
