# Generated by Django 2.0.6 on 2018-06-20 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.User')),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
